services:
  cmake-vcpkg-demo:
    build:
      context: .
      dockerfile: Dockerfile
    # image: "lianglliu/cpp-dev-container:1.0.0"
    container_name: cpp-dev-container
    volumes:
      - .:/workspace/cmake-vcpkg-demo
    stdin_open: true
    tty: true
    command: /bin/bash
    deploy:
      resources:
        limits:
          cpus: '5.0'
          memory: 6G
    working_dir: /workspace/cmake-vcpkg-demo
    shm_size: '2gb'

